<div class="row mb-3 ml-0 p-0">
    <div class="m-0 pl-0">
        <label for="roundSelect" class="col pl-0">Round</label>
        <select class="custom-select" id="roundSelect" style="width:auto;">
            @php $selected = $round_param ?? 'all'; @endphp
            <option value='all' {{$selected == 'all' ? 'selected' : ''}}>---</option>
            @foreach (range(1,2) as $round)
                <option {{$selected == $round ? 'selected' : ''}}>{{$round}}</option>
            @endforeach
        </select>
    </div>
    <div class="m-0 pl-0">
        <label for="weekSelect" class="col pl-0">Week</label>
        <select class="custom-select" id="weekSelect" style="width:auto;">
            @php
                $selected_round = $round_param ?? 'all';
                $selected = $week_param ?? 'all';
                $weeks_per_round = $weeks_count / 2;
                if ($selected_round != 'all'){
                    $available_weeks = range( ( $selected_round - 1 ) * $weeks_per_round + 1 , $selected_round * $weeks_per_round);
                } else {
                    $available_weeks = range(1, $weeks_count);
                }
            @endphp
            <option value='all' {{$selected == 'all' ? 'selected' : ''}}>---</option>
            @foreach ($available_weeks as $week)
                <option {{$selected == $week ? 'selected' : ''}}>{{$week}}</option>
            @endforeach
        </select>
    </div>
    <div class="m-0 pl-0">
        <label for="teamSelect" class="col pl-0">Team</label>
        <select class="custom-select" id="teamSelect" style="width:auto;">
            @php $selected = $team_id_param ?? 'all'; @endphp
            <option value='all' {{$selected == 'all' ? 'selected' : ''}}>---</option>
            @foreach ($teams_by_id as $id => $team_name)
                <option value="{{$id}}" {{$selected == $id ? 'selected' : null}}>{{$team_name}}</option>
            @endforeach
        </select>
    </div>
    <div class="col-3 mt-auto p-0">
        <button id="reset_filters" type="button" class="btn btn-secondary">Reset Filters</button>
    </div>
</div>
{{-- #NOTE each input should be generated by a 'dropdown' blade
#NOTE IDs, labels & classes shouud be passed as params --}}